baseurl                  = "https://lucaszhu97.github.io"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Lucas Zhu"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "ukraine-2.png"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty

# Metadata for Open Graph and Twitter
    description          = "Lucas Zhu's Homepage."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Lucas Zhu"
    # rss                = ""

[[params.mainMenu]]
    link = "about"
    text = "about"

[[params.mainMenu]]
    link = "recent"
    text = "recent"

[[params.mainMenu]]
    link = "post"
    text = "post"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"

[imaging]
    quality = 100
